app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='home'),
    path('news', views.news, name='news'),
    path('players', views.players, name='players'),
    path('players/<int:player_id>', views.player, name='player'),
    path('duels', views.duels, name='duels'),
    path('scores', views.scores, name='scores'),
    path('standing', views.standing, name='standing'),
    path('teams', views.teams, name='teams'),
    path('teams/<int:team_id>', views.team, name='team'),
]

app/models.py
from django.db import models

class Team(models.Model):
    team_id = models.IntegerField(db_column='id', primary_key=True)
    city = models.CharField(max_length=13)
    full_name = models.CharField(db_column='fullName', max_length=22)
    nick_name = models.CharField(db_column='nickName', max_length=13)
    logo = models.CharField(max_length=138)
    short_name = models.CharField(db_column='shortName', max_length=3)
    conf_name = models.CharField(db_column='confName', max_length=4)
    div_name = models.CharField(db_column='divName', max_length=9)

    def __str__(self):
        return self.full_name
    
    class Meta:
        managed = False
        db_table = 'teams'

class Player(models.Model):
    id = models.IntegerField(primary_key=True)
    first_name = models.CharField(db_column='firstName', max_length=12)
    last_name = models.CharField(db_column='lastName', max_length=18, blank=True, null=True)
    team = models.ForeignKey(Team, db_column='teamId', on_delete=models.CASCADE)
    years_pro = models.IntegerField(db_column='yearsPro')
    college_name = models.CharField(db_column='collegeName', max_length=34, blank=True, null=True)
    country = models.CharField(max_length=32, blank=True, null=True)
    dob = models.DateField(db_column='DOB', blank=True, null=True)
    affiliation = models.CharField(max_length=50, blank=True, null=True)
    height_in_meters = models.DecimalField(db_column='heightInMeters', max_digits=4, decimal_places=2, blank=True, null=True)
    weight_in_kilograms = models.DecimalField(db_column='weightInKilograms', max_digits=5, decimal_places=1, blank=True, null=True)
    pos = models.CharField(max_length=3, blank=True, null=True)

    def __str__(self):
        return self.first_name + ' ' + self.last_name

    class Meta:
        managed = False
        db_table = 'players'

class Game(models.Model):
    game_id = models.IntegerField(primary_key=True)
    home_team = models.ForeignKey(Team, on_delete=models.CASCADE, related_name='home')
    away_team = models.ForeignKey(Team, on_delete=models.CASCADE, related_name='away')
    date_time = models.CharField(max_length=50)
    home_score = models.IntegerField()
    away_score = models.IntegerField()

class Standing(models.Model):
    team = models.OneToOneField(Team, primary_key=True, on_delete=models.CASCADE)
    win = models.IntegerField()
    loss = models.IntegerField()
    conference = models.CharField(max_length=4)
    conference_rank = models.IntegerField()
    division = models.CharField(max_length=20)
    division_rank = models.IntegerField()

app/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, JsonResponse
from django.template import loader
from .models import Game, Player, Standing, Team
from .serializers import TeamSerializer, GameSerializer, PlayerSerializer, StandingSerializer
from .api.duels import load_duels

def index(request):
    return render(request, 'stats/index.html')

def player(request, player_id):
    if request.method == 'GET':
        player = get_object_or_404(Player, pk=player_id)
        serializer = PlayerSerializer(player, many=False)
    return JsonResponse(serializer.data, safe=False)

def players(request):
    if request.method == 'GET':
        players = Player.objects.all()
        position = request.GET.get('pos', None)
        if position is not None:
            players = players.filter(pos=position)
        serializer = PlayerSerializer(players, many=True)
    return JsonResponse(serializer.data, safe=False)

def news(request):
    return render(request, 'stats/news.html')

def duels(request):
    duels = load_duels()
    context = {
        'duels': duels
    }
    return render(request, 'stats/duels.html', context)

def scores(request):
    scores = Game.objects.all()
    serializer = GameSerializer(scores, many=True)
    return JsonResponse(serializer.data, safe=False)

def standing(request):
    if request.method == 'GET':
        standing = Standing.objects.all()
        conference = request.GET.get('conference', None)
        if conference == 'west':
            standing = standing.filter(conference = 'west').order_by('-win')
        elif conference == 'east':
            standing = standing.filter(conference = 'east').order_by('-win')
        serializer = StandingSerializer(standing, many=True)
        return JsonResponse(serializer.data, safe=False)

def team(request, team_id):
    if request.method == 'GET':
        team = get_object_or_404(Team, pk=team_id)
        serializer = TeamSerializer(team, many=False)
    return JsonResponse(serializer.data, safe=False)

def teams(request):
    if request.method == 'GET':
        teams = Team.objects.all()
        serializer = TeamSerializer(teams, many=True)
    return JsonResponse(serializer.data, safe=False)

app/templates/players/index.html
{% extends 'stats/base.html' %}
{% block content %} 
    <div class="column-container">
        <select class="ui fluid dropdown players">
            <option value="">Select a Position</option>
            {% for position in positions.keys %}
                <option value="{{ position }}">{{ position }}</option>
            {% endfor %}
        </select>
        {% for position, players in positions.items %}
        <div class="ui styled fluid accordion {{ position }}">
        {% for player in players %}
            <div class="title">
            <i class="dropdown icon"></i>
            {{ player }}
            </div>
            <div class="content">
                {% if player.pos %}<p>Position: {{ player.pos }}</p>{% endif %}
                {% if player.height_in_meters %}<p>Height: {{ player.height_in_meters }}m</p>{% endif %}
                {% if player.weight_in_kilograms %}<p>Weight: {{ player.weight_in_kilograms }}kg</p>{% endif %}
                {% if player.dob %}<p>Date of Birth: {{ player.dob }}</p>{% endif %}
                {% if player.country %}<p>Country: {{ player.country }}</p>{% endif %}
                {% if player.years_pro %}<p>Years pro: {{ player.years_pro }}</p>{% endif %}
            </div>
        {% endfor %}
        </div>
        {% endfor %}
    </div>
{% endblock content %}
{% block script %}
    <script language="javascript">
        $(document).ready(function(){
            $('.dropdown').dropdown();
            $('.ui.accordion').accordion();
            $(".ui.dropdown").change(function(){
            var selectedPosition = $('.ui.dropdown option:selected').val();
            $('.accordion').not(`.${selectedPosition}`).hide();
            $(`.${selectedPosition}`).show();
        }); 
        });
    </script>
{% endblock script %}

app/templates/players/player.html
{% extends 'stats/base.html' %}
{% block content %}
<div class="ui midsize-container centered-flex-container">
    <h1>{{ team.nick_name }}</h1>
    <div class="ui styled fluid accordion">
    {% for player in team.player_set.all %}
        <div class="title">
        <i class="dropdown icon"></i>
        {{ player }}
        </div>
        <div class="content">
            {% if player.pos %}<p>Position: {{ player.pos }}</p>{% endif %}
            {% if player.height_in_meters %}<p>Height: {{ player.height_in_meters }}m</p>{% endif %}
            {% if player.weight_in_kilograms %}<p>Weight: {{ player.weight_in_kilograms }}kg</p>{% endif %}
            {% if player.dob %}<p>Date of Birth: {{ player.dob }}</p>{% endif %}
            {% if player.country %}<p>Country: {{ player.country }}</p>{% endif %}
            {% if player.years_pro %}<p>Years pro: {{ player.years_pro }}</p>{% endif %}
        </div>
    {% endfor %}
    </div>
</div>
{% endblock content %}

app/templates/stats/base.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        {% block style %}
        {% endblock style%}
        <link rel="stylesheet" type="text/css" href="{% static 'stylesheets/accordion.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'stylesheets/card.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'stylesheets/dropdown.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'stylesheets/table.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'stylesheets/transition.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'stats/header.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'stats/footer.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'stats/style.css' %}">
        <script
            src="https://code.jquery.com/jquery-3.1.1.min.js"
            integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="
            crossorigin="anonymous"></script>
        <script src="{% static 'scripts/semantic.min.js' %}"></script>
    </head>
    <body>
        <header>
            <h1><span class="logoWhite">Hoop</span><span class="logoRed">France</span></h1>
            <input type="checkbox" id="nav-toggle" class="nav-toggle"/>
            <nav>
                <ul>
                    <li><a href="{% url 'scores' %}">Scores</a></li>
                    <li><a href="{% url 'duels' %}">Duels</a></li>
                    <li><a href="{% url 'standing' %}">Standings</a></li>
                    <li><a href="{% url 'players' %}">Players</a></li>
                    <li><a href="{% url 'teams' %}">Teams</a></li>
                </ul>
            </nav>
            <label for="nav-toggle" class="nav-toggle-label">
                <span></span>
            </label>
        </header>
        <div class="content-block">
            {% block content %}
            {% endblock content %}
        </div>
        <footer class="footer-container border-top ml-1 mr-1 pt-3 pb-3">
            <ul class="list-style-none d-flex flex-wrap">
                <li class="mr-3 text-gray">&copy 2020, HoopFrance, Inc.</li>
                <li class="mr-3"><a href="{% url 'scores' %}">Scores</a></li>
                <li class="mr-3"><a href="{% url 'duels' %}">Duels</a></li>
            </ul>
            <p class="ml-3"><a href="{% url 'home' %}"><span class="logoBlue">Hoop</span><span class="logoRed">France</span></a></p>
            <ul class="list-style-none d-flex flex-wrap">
                <li class="mr-3"><a href="{% url 'standing' %}">Standings</a></li>
                <li class="mr-3"><a href="{% url 'players' %}">Players</a></li>
                <li class="mr-3"><a href="{% url 'teams' %}">Teams</a></li>
            </ul>
        </footer>
        {% block script %}
        {% endblock %}
    </body>
</html>

app/templates/stats/duels.html
{% extends 'stats/base.html' %}
{% load static %}
{% block style %}
<link rel="stylesheet" type="text/css" href="{% static 'stats/duels.css' %}">
{% endblock %}
{% block content %}
<div class="column-container">
    <section id="video">
        <iframe 
            width="800px"
            height="450px"
            src="https://www.youtube.com/embed/{{ duels.0.snippet.resourceId.videoId }}" 
            frameborder="0" 
            allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" 
            allowfullscreen>
        </iframe>
    </section>
    <main>
        {% for duel in duels %}
            <article class="item " data-key="{{ duel.snippet.resourceId.videoId }}">
                <img src="{{ duel.snippet.thumbnails.medium.url }}" alt="" class="thumb">
                <div class="details">
                    <h4>{{ duel.snippet.title }}</h4>
                    <p>{{ duel.snippet.description|slice:'0:140'|add:'...' }}</p>
                </div>
            </article>
        {% endfor %}
    </main>
</div>
{% endblock content %}
{% block script %}
<script src="{% static 'scripts/duels.js'%}">

</script>
{% endblock script %}

app/templates/stats/index.html
{% extends 'stats/base.html' %}

app/templates/stats/scores.html
{% extends 'stats/base.html' %}
{% block content %} 
    <div>
      <table class="ui single line table">
        <thead>
            <tr>
                <th>Home</th>
                <th></th>
                <th></th>
                <th></th>
                <th>Away</th>
            </tr>
        </thead>
        <tbody>
            {% for score in scores %}
            <tr>
                <td>{{ score.home_team.nick_name }} </td>
                <td>{{ score.home_score }}</td>
                <td> - </td>
                <td>{{ score.away_score }}</td>
                <td>{{ score.away_team.nick_name }}</td>
            </tr>
            {% endfor %}
        </tbody>
      </table>
    </div>
{% endblock content %}

app/templates/stats/standing.html
{% extends 'stats/base.html' %}
{% block content %} 
    <div>
        <select class="ui fluid dropdown">
            <option value="">Select a Conference</div>
            {% for conference in conferences.keys %}
                <option value="{{ conference }}">{{ conference }}</option>
            {% endfor %}
        </select>
        {% for conference, teams in conferences.items %}
        <table class="ui single line table {{ conference }}">
            <thead>
                <tr>
                    <th>Rank</th>
                    <th>Team</th>
                    <th>Wins</th>
                    <th>Losses</th>
                    <th>Division</th>
                </tr>
            </thead>
            <tbody>
                {% for team in teams %}
                <tr>
                    <td>{{ team.conference_rank }}</td>
                    <td>{{ team.team.full_name }}</td>
                    <td>{{ team.win }}</td>
                    <td>{{ team.loss }}</td>
                    <td>{{ team.division }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% endfor %}
    </div>
{% endblock content %}
{% block script %}
<script language="javascript">
    $(document).ready(function(){
        $('.dropdown').dropdown();
        $(".ui.dropdown").change(function(){
            var selectedConference = $('.ui.dropdown option:selected').val();
            $('.table').not(`.${selectedConference}`).hide();
            $(`.${selectedConference}`).show();
        }); 
    });
</script>
{% endblock %}

app/templates/teams/index.html
{% extends 'stats/base.html' %}
    {% block content %}
        {% if team_list %}
        <div class="ui cards centered-flex-container">
            
        {% for team in team_list %}
            <div class="card">
                <div class="image card-img">
                <img src="https://stats.nba.com/media/img/teams/logos/{{ team.short_name }}_logo.svg">
                </div>
                <div class="content">
                <div class="header">{{ team.full_name }}</div>
                <div class="meta">
                    <a href="{% url 'team' team.team_id %}">See Roster</a>
                </div>
                <div class="description">
                    
                </div>
                </div>
                <div class="extra content">
                <span class="right floated">
                    <a>D. -> {{ team.div_name }}</a>
                </span>
                <span>
                    <a>C. -> {{ team.conf_name }}</a>
                </span>
                </div>
            </div>
        {% endfor %}
        </div>
        {% else %}
            <p>No teams are available.</p>
        {% endif %}
    {% endblock content %}
    

app/templates/teams/team.html
{% extends 'stats/base.html' %}
{% block content %}
<div class="ui midsize-container centered-flex-container">
    <h1>{{ team.nick_name }}</h1>
    <div class="ui styled fluid accordion">
    {% for player in team.player_set.all %}
        <div class="title">
        <i class="dropdown icon"></i>
        {{ player }}
        </div>
        <div class="content">
            {% if player.pos %}<p>Position: {{ player.pos }}</p>{% endif %}
            {% if player.height_in_meters %}<p>Height: {{ player.height_in_meters }}m</p>{% endif %}
            {% if player.weight_in_kilograms %}<p>Weight: {{ player.weight_in_kilograms }}kg</p>{% endif %}
            {% if player.dob %}<p>Date of Birth: {{ player.dob }}</p>{% endif %}
            {% if player.country %}<p>Country: {{ player.country }}</p>{% endif %}
            {% if player.years_pro %}<p>Years pro: {{ player.years_pro }}</p>{% endif %}
        </div>
    {% endfor %}
    </div>
</div>
{% endblock content %}